import { Link, useLocation } from "wouter";
import { SEO, schemas } from "@/components/SEO";
import { useLang } from "@/contexts/LangContext";
import { canonicalUrl } from "@/lib/seo-url";

const data = {
  "/router-4g-moldova": {
    ro: ["Router 4G cu SIM în Moldova | TECO.md","Router 4G cu cartelă SIM în Moldova","Cauți internet 4G fără cablu, router cu SIM sau un model Cudy? Trimite modelul sau cerințele și verificăm disponibilitatea înainte de comandă.",["Router 4G cu SIM","Pentru casă, șantier sau altă locație fără internet fix, alegerea depinde de acoperirea operatorului, benzile LTE, Wi-Fi și numărul de dispozitive."],["Cudy și alte modele","Dacă ai nevoie de Cudy AX1800, AC1200, mesh, repeater sau alt model, indică denumirea exactă. Nu afișăm stoc neverificat; confirmăm disponibilitatea și prețul înainte de comandă."]],
    ru: ["4G роутер с SIM-картой в Молдове | TECO.md","4G роутер с SIM-картой в Молдове","Ищете 4G интернет без кабеля, роутер с SIM или Cudy? Укажите модель или требования — наличие и цена подтверждаются перед заказом.",["4G роутер с SIM","Для дома, стройки или объекта без проводного интернета учитываются покрытие оператора, LTE диапазоны, Wi-Fi и количество устройств."],["Cudy и другие модели","Если нужен Cudy AX1800, AC1200, mesh, repeater или другая модель, укажите точное название. Непроверенное наличие не показываем; цену и доступность подтверждаем до заказа."]]
  },
  "/cablu-utp-ftp-moldova": {
    ro: ["Cablu UTP / FTP pentru Internet și Camere | TECO.md","Cablu UTP și FTP în Moldova","Ai nevoie de cablu Cat5e, Cat6 sau cablu de exterior pentru rețea ori camere IP? Spune lungimea, mediul de instalare și echipamentele; verificăm varianta și disponibilitatea.",["UTP sau FTP?","Alegerea depinde de traseu, interferențe, exterior/interior, lungime și cerințele echipamentelor. Pentru PoE contează și calitatea conductorului și conexiunilor."],["Pentru camere IP și PoE","Putem include cablul în devizul unei instalații de supraveghere. Lungimea și traseul se estimează separat, iar materialele se confirmă înainte de lucrare."]],
    ru: ["Кабель UTP / FTP для сети и камер | TECO.md","Кабель UTP и FTP в Молдове","Нужен Cat5e, Cat6 или наружный сетевой кабель для IP камер? Укажите длину, условия прокладки и оборудование — тип и наличие подтверждаются перед заказом.",["UTP или FTP?","Выбор зависит от трассы, помех, улицы или помещения, длины и требований оборудования. Для PoE важны качество проводника и соединений."],["Для IP и PoE камер","Кабель можно включить в смету системы видеонаблюдения. Длина и трасса рассчитываются отдельно, материалы подтверждаются до работ."]]
  },
  "/interfoane-moldova": {
    ro: ["Interfoane și Video Interfoane în Moldova | TECO.md","Interfoane și video interfoane în Moldova","Pentru casă, apartament, poartă sau birou putem evalua cerința pentru interfon ori video-interfon. Trimite tipul obiectului și funcțiile dorite; disponibilitatea echipamentului se confirmă înainte de ofertă.",["Ce sistem îți trebuie?","Contează numărul de intrări, postul interior, camera, deschiderea yalei, cablarea existentă și dacă dorești acces din aplicație. Compatibilitatea se verifică pentru modelele propuse."],["Ofertă fără stoc inventat","Nu prezentăm un model ca fiind disponibil dacă nu este confirmat în catalog sau la furnizor. Trimite cerința și primești configurația și prețul actual înainte de comandă."]],
    ru: ["Домофоны и видеодомофоны в Молдове | TECO.md","Домофоны и видеодомофоны в Молдове","Для дома, квартиры, ворот или офиса можно подобрать домофон или видеодомофон. Укажите объект и нужные функции; наличие оборудования подтверждается до предложения.",["Какая система нужна?","Учитываются количество входов, внутренний монитор, камера, управление замком, существующий кабель и необходимость доступа через приложение. Совместимость проверяется для выбранных моделей."],["Предложение без выдуманного наличия","Мы не указываем модель в наличии без подтверждения в каталоге или у поставщика. Отправьте требования — конфигурация и актуальная цена согласуются до заказа."]]
  }
} as const;

export default function LegacyDemand() {
 const [loc]=useLocation(); const path=loc.replace(/\/$/,"") as keyof typeof data; const {lang}=useLang(); const d=(data[path]||data["/router-4g-moldova"])[lang];
 const [title,heading,intro,s1,s2]=d;
 return <><SEO title={title} description={intro} canonical={path} lang={lang} jsonLd={[schemas.breadcrumb([{name:"TECO.md",url:canonicalUrl("/")},{name:heading,url:canonicalUrl(path)}])]} />
 <main className="flex-1 bg-[#FAFAFA]"><section className="bg-zinc-950 text-white py-14 md:py-20"><div className="max-w-5xl mx-auto px-5 md:px-8"><h1 className="text-3xl md:text-5xl font-black">{heading}</h1><p className="mt-6 text-zinc-300 text-lg max-w-3xl">{intro}</p><Link href="/oferta/" className="inline-flex mt-8 bg-[#FF4F00] rounded-xl px-6 py-3 font-bold">{lang==="ro"?"Verifică disponibilitatea / cere ofertă":"Проверить наличие / запросить предложение"}</Link></div></section>
 <section className="max-w-5xl mx-auto px-5 md:px-8 py-12 grid md:grid-cols-2 gap-5">{[s1,s2].map(x=><article key={x[0]} className="bg-white border border-zinc-200 rounded-2xl p-6"><h2 className="text-xl font-bold">{x[0]}</h2><p className="mt-3 text-zinc-600 leading-relaxed">{x[1]}</p></article>)}</section>
 <section className="max-w-5xl mx-auto px-5 md:px-8 pb-16 flex gap-4 flex-wrap"><Link href="/oferta/" className="font-semibold text-[#FF4F00] underline">{lang==="ro"?"Cere ofertă":"Запросить предложение"}</Link><Link href="/camere-supraveghere-moldova/" className="font-semibold text-[#FF4F00] underline">{lang==="ro"?"Camere de supraveghere":"Камеры видеонаблюдения"}</Link><Link href="/servicii/" className="font-semibold text-[#FF4F00] underline">{lang==="ro"?"Servicii":"Услуги"}</Link></section></main></>;
}
